version: '2'
services:
  db:
    image: postgres:alpine
    command: -c fsync=off # *** don't use in production! ***
  web:
    build: .
    image: fnix/web
    user: skywalker # user_id:group_id
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/xwing
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  spring:
    build: .
    image: fnix/web
    user: skywalker # user_id:group_id
    volumes:
      - .:/xwing
      - bundle:/usr/local/bundle
    command: spring server

    # This ensures that the pid namespace is shared between the host
    # and the container. It's not necessary to be able to run spring
    # commands, but it is necessary for "spring status" and "spring stop"
    # to work properly.
    pid: host
volumes:
  bundle:
